### ISSUE TITLE
make install fails on Mac OSX

### ISSUE THREAD

**Issue by Siddhant** [openvenues/libpostal#310]
Hi! I was trying to build libpostal on Mac OSX, but the process failed at the make install step with the following error:

---
#### Here's what I did
```
$ sudo make install
```
---
#### Here's what I got
```
Password:
Making install in src
./libpostal_data download all /Users/agund1/Data/SID/libpostal_dir/libpostal
Checking for new libpostal data file...
libpostal data file up to date
make[1]: *** [all-local] Error 7
make: *** [install-recursive] Error 1
```
---
### System details
Mac OSX version 10.12.6

Please let me know if any other details are required.

**Comment by albarrentine** [comment]
From #287 (different platform, same issue): you can run `./src/libpostal_data download all /Users/agund1/Data/SID/libpostal_dir/libpostal` to diagnose the error further.

Error code 7 is CURLE_COULDNT_CONNECT, so it means the machine can't connect to the Internet or there's a firewall in place. Try fixing the Internet issue and then doing a fresh install.

**Comment by Siddhant** [comment]
It says "libpostal data file up to date" in the output of "make install". That's confusing.
Doesn't that mean that all data files have been downloaded and up to date?

**Comment by Siddhant** [comment]
I also tried your suggestion.
Without doing any changes, the command you suggested works, but make install still does not:

```
$ ./src/libpostal_data download all /Users/agund1/Data/SID/libpostal_dir/libpostal
Checking for new libpostal data file...
New libpostal data file available
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9.8M  100  9.8M    0     0   515k      0  0:00:19  0:00:19 --:--:--  348k
x address_expansions/
x address_expansions/address_dictionary.dat
x numex/
x numex/numex.dat
x transliteration/
x transliteration/transliteration.dat
Checking for new libpostal parser data file...
libpostal parser data file up to date
Checking for new libpostal language classifier data file...
libpostal language classifier data file up to date
$ sudo make install
Password:
Making install in src
./libpostal_data download all /Users/agund1/Data/SID/libpostal_dir/libpostal
Checking for new libpostal data file...
libpostal data file up to date
make[1]: *** [all-local] Error 7
make: *** [install-recursive] Error 1
```

What next?

**Comment by thunter009** [comment]
I am running into the same issue on MacOSX 10.13.3. I ran the suggested provided by @albarrentine  above but am still getting similar errors to above:

> Making install in src
> ./libpostal_data download all /Users/thom/libpostal/tmp/libpostal
> Checking for new libpostal data file...
> libpostal data file up to date
> Checking for new libpostal parser data file...
> libpostal parser data file up to date
> Checking for new libpostal language classifier data file...
> libpostal language classifier data file up to date
>  .././install-sh -c -d '/usr/local/bin'
>  /usr/bin/install -c libpostal_data '/usr/local/bin'
>  .././install-sh -c -d '/usr/local/lib'
>  /bin/sh ../libtool   --mode=install /usr/bin/install -c   libpostal.la '/usr/local/lib'
> libtool: install: /usr/bin/install -c .libs/libpostal.1.dylib /usr/local/lib/libpostal.1.dylib
> libtool: install: (cd /usr/local/lib && { ln -s -f libpostal.1.dylib libpostal.dylib || { rm -f libpostal.dylib && ln -s libpostal.1.dylib libpostal.dylib; }; })
> libtool: install: /usr/bin/install -c .libs/libpostal.lai /usr/local/lib/libpostal.la
> libtool: install: /usr/bin/install -c .libs/libpostal.a /usr/local/lib/libpostal.a
> libtool: install: chmod 644 /usr/local/lib/libpostal.a
> libtool: install: ranlib /usr/local/lib/libpostal.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /usr/local/lib/libpostal.a(libpostal_la-strndup.o) has no symbols
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /usr/local/lib/libpostal.a(libscanner_la-drand48.o) has no symbols
>  .././install-sh -c -d '/usr/local/include/libpostal'
>  /usr/bin/install -c -m 644 libpostal.h '/usr/local/include/libpostal'
> Making install in test
> make[2]: Nothing to be done for `install-exec-am'.
> make[2]: Nothing to be done for `install-data-am'.
> make[2]: Nothing to be done for `install-exec-am'.
>  ./install-sh -c -d '/usr/local/lib/pkgconfig'
>  /usr/bin/install -c -m 644 libpostal.pc '/usr/local/lib/pkgconfig'

**Comment by albarrentine** [comment]
Ok, first remove the datadir, then run the command I mentioned.

**Comment by onekiloparsec** [comment]
So to resume, the installation process goes as follow:
- `./src/libpostal_data download all <datadir>`
- `./configure --datadir=<datadir> --disable-data-download`
- `make -j4`

Apparently, it worked on my machine (untested the results yet).
Rather curiously, after this line:
`Downloading part 11: filename=/Volumes/200GB/libpostal-data//parser.tar.gz.11, offset=671088640, max=752483239`
the download continued for a while (according to my network monitor), then finished, and no message is printed for 1-2 minutes, but then it moves on with:
```
x address_parser/
x address_parser/address_parser_crf.dat
x address_parser/address_parser_phrases.dat
```
etc... and finally succeeds.

**Comment by onekiloparsec** [comment]
There is a tricky part I forgot to mention ! The command `./src/libpostal_data download all <datadir>` doesn't append `libpostal` to the datadir. It put files exactly where we told it to do.

However, if we put the same `datadir` in the `configure` command, it appends a `libpostal` to it. Hence, one must first move the downloaded data into a `libpostal` subfolder, and *doesn't* specify it in the `./configure` command.

**Comment by onekiloparsec** [comment]
Still, doesn't work... 
```
Python 3.6.4 (default, Jan  6 2018, 11:51:59) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from postal.parser import parse_address
ERR   Error loading transliteration module, dir=(null)
   at libpostal_setup_datadir (libpostal.c:266) errno: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/onekiloparsec/.virtualenvs/arcsecond-debug-py3/lib/python3.6/site-packages/postal/parser.py", line 2, in <module>
    from postal import _parser
SystemError: initialization of _parser raised unreported exception
```

**Comment by onekiloparsec** [comment]
I succeded by moving the data into another `libpostal` directory... The final one is:
`<datadir>/libpostal/libpostal/`

**Comment by onekiloparsec** [comment]
Sorry, for practical reasons, I decided to move on without libpostal.

**Comment by naolenikhil** [comment]
I got the same error. I created a datadir under libpostal directory. When I moved the datadir to outside of libpostal directory, it worked. Not sure why. I didn't dig into the code but this worked for me.

**Comment by rileyhun** [comment]
I also got the same error and I tried it w/ the datadir outside of the libpostal directory as well. It should be noted that I tried the installation on an AI Platform Notebook

**Comment by MattCowgill** [comment]
Does anyone have straightforward, working instructions to install `libpostal` on macOS? I'm struggling with this. Thanks
